### ISSUE TITLE
KeyError: 'appearance'

### ISSUE THREAD

**Issue by pavlinbl4** [dnigamer/TeraboxUploaderCLI#7]
**Describe the bug**

**To Reproduce**
1. Go to main.py and start it
2. settings.json
{
  "directories": {
    "sourcedir": "/Volumes/big4photo-4/to_trash",
    "remotedir": "root/2024",
    "uploadeddir": "/Volumes/big4photo-4/2024"
  },
  "files": {
    "movefiles": "true",
    "deletesource": "false"
  },
  "encryption": {
    "enabled": "false",
    "encryptionkey": "your_encryption_key_here"
  },
  "ignoredfiles": []
}
4. Get
 Traceback (most recent call last):
  File "/Volumes/big4photo/_PYTHON/TeraboxUploaderCLI/main.py", line 140, in <module>
    SHOWQUOTA = settings["appearance"]["showquota"].lower() == "true"
                ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'appearance'



**Screenshots**
![Screenshot 2024-06-09 at 14 49 38](https://github.com/dnigamer/TeraboxUploaderCLI/assets/66327439/473f614b-d468-4c8e-bb94-5cec4637aedf)



**Desktop (please complete the following information):**
 - OS: macOS 12.6.3 (21G419)
 - Browser Brave
 - [Version 1.65.133 Chromium: 124.0.6367.208 (Official Build) (x86_64)](https://brave.com/latest/)
 - Python 3.11

**Comment by pavlinbl4** [comment]
Check your `settings.json` file: Open the `settings.json` file and verify that it contains the `"appearance"` section and the `"showquota"` key within it. The structure should look something like this:
```python

``` {
    "directories": {
        "sourcedir": "...",
        "remotedir": "...",
        "uploadeddir": "..."
    },
    "files": {
        "movefiles": "true",
        "deletesource": "true"
    },
    "encryption": {
        "enabled": "true",
        "encryptionkey": "..."
    },
    "appearance": {
        "showquota": "true"
    },
    "ignoredfiles": ["...", "..."]
}

**Comment by dnigamer** [comment]
Hello! Thank you for reporting an issue on the program.
I'm aware of this problem and the solution to solve it, but still haven't got around to fix it. The solution you gave is valid and is actually the correct procedure to do to be able to run the program, in the current version. I will be adding to the documentation soon the new settings structure and some other fail saves for the json files.
